export const nodeHandles = {
  Start: { left: [], right: ["out"] },
  VariableGet: { left: [], right: ["out-get"] },
  ParameterGet: { left: [], right: ["out-get"] },
  VariableSet: { left: ["in", "in-get"], right: ["out"] },
  ConsoleLog: { left: ["in", "in-get"], right: ["out"] },
  IFBranch: { left: ["in", "in-boolean"], right: ["out-true", "out-false"] },
  Compare: {
    left: ["in-get-left", "in-get-right"],
    right: ["out-get-boolean"],
  },
  Gate: { left: ["in-get-left", "in-get-right"], right: ["out-get-boolean"] },
  StringInput: { left: [], right: ["out-get-string"] },
  NumericInput: { left: [], right: ["out-get-numeric"] },
  BooleanInput: { left: [], right: ["out-get-boolean"] },
  Return: { left: ["in", "in-get"], right: [] },
  GetElement: { left: [], right: ["out-get-block"] },
  GetElementAttribute: { left: ["in-get-block"], right: ["out-get-string"] },
  SetElementAttribute: { left: ["in", "in-get-block"], right: ["out"] },
};
